import type { Trip } from "./types";

export const seedTrips: Trip[] = [
  {
    id: "trip-lisbon-2026",
    name: "Spring reset in Lisbon",
    destination: "Lisbon",
    country: "Portugal",
    startDate: "2026-03-14",
    endDate: "2026-03-18",
    currency: "EUR",
    travelStyle: "city-break",
    summary: "A relaxed city break where lodging stayed high but food was easy to control.",
    categoryTotals: [
      { categoryId: "lodging", amountCents: 62000, note: "Apartment near Baixa." },
      { categoryId: "food", amountCents: 28500, note: "Coffee and casual dinners." },
      { categoryId: "transport", amountCents: 18000, note: "Flights and metro card." },
      { categoryId: "activities", amountCents: 15000, note: "Museums and viewpoints." },
      { categoryId: "shopping", amountCents: 7000 },
      { categoryId: "admin", amountCents: 3500 },
      { categoryId: "misc", amountCents: 5000 },
    ],
  },
  {
    id: "trip-istanbul-2026",
    name: "Long weekend in Istanbul",
    destination: "Istanbul",
    country: "Turkiye",
    startDate: "2026-05-01",
    endDate: "2026-05-07",
    currency: "EUR",
    travelStyle: "slow-trip",
    summary: "A longer trip with more activities and steady local transport costs.",
    categoryTotals: [
      { categoryId: "lodging", amountCents: 69000 },
      { categoryId: "food", amountCents: 42000 },
      { categoryId: "transport", amountCents: 31000 },
      { categoryId: "activities", amountCents: 26000 },
      { categoryId: "shopping", amountCents: 18000 },
      { categoryId: "admin", amountCents: 9000 },
      { categoryId: "misc", amountCents: 6500 },
    ],
  },
  {
    id: "trip-tbilisi-2026",
    name: "Tbilisi food notes",
    destination: "Tbilisi",
    country: "Georgia",
    startDate: "2026-02-08",
    endDate: "2026-02-11",
    currency: "EUR",
    travelStyle: "city-break",
    summary: "A compact lower-cost trip, mostly because lodging and activities were modest.",
    categoryTotals: [
      { categoryId: "lodging", amountCents: 28000 },
      { categoryId: "food", amountCents: 22000 },
      { categoryId: "transport", amountCents: 19000 },
      { categoryId: "activities", amountCents: 12000 },
      { categoryId: "shopping", amountCents: 6500 },
      { categoryId: "admin", amountCents: 3000 },
      { categoryId: "misc", amountCents: 4500 },
    ],
  },
  {
    id: "trip-copenhagen-2025",
    name: "Design week in Copenhagen",
    destination: "Copenhagen",
    country: "Denmark",
    startDate: "2025-09-11",
    endDate: "2025-09-15",
    currency: "EUR",
    travelStyle: "event-trip",
    summary: "Short and expensive, with tickets and food pushing the daily average up.",
    categoryTotals: [
      { categoryId: "lodging", amountCents: 78000 },
      { categoryId: "food", amountCents: 47500 },
      { categoryId: "transport", amountCents: 26000 },
      { categoryId: "activities", amountCents: 35000 },
      { categoryId: "shopping", amountCents: 12000 },
      { categoryId: "admin", amountCents: 4000 },
      { categoryId: "misc", amountCents: 6000 },
    ],
  },
  {
    id: "trip-valencia-2025",
    name: "Valencia slow days",
    destination: "Valencia",
    country: "Spain",
    startDate: "2025-06-03",
    endDate: "2025-06-09",
    currency: "EUR",
    travelStyle: "slow-trip",
    summary: "Good balance: lower lodging, higher food, and very little admin overhead.",
    categoryTotals: [
      { categoryId: "lodging", amountCents: 54000 },
      { categoryId: "food", amountCents: 36500 },
      { categoryId: "transport", amountCents: 20500 },
      { categoryId: "activities", amountCents: 15500 },
      { categoryId: "shopping", amountCents: 8500 },
      { categoryId: "admin", amountCents: 2500 },
      { categoryId: "misc", amountCents: 5500 },
    ],
  },
  {
    id: "trip-porto-2025",
    name: "Porto notes",
    destination: "Porto",
    country: "Portugal",
    startDate: "2025-11-20",
    endDate: "2025-11-23",
    currency: "EUR",
    travelStyle: "city-break",
    summary: "A compact trip where transport was high relative to total days.",
    categoryTotals: [
      { categoryId: "lodging", amountCents: 36000 },
      { categoryId: "food", amountCents: 21500 },
      { categoryId: "transport", amountCents: 23500 },
      { categoryId: "activities", amountCents: 9000 },
      { categoryId: "shopping", amountCents: 4000 },
      { categoryId: "admin", amountCents: 2500 },
      { categoryId: "misc", amountCents: 3000 },
    ],
  },
];
